# Generated by Django 3.0.4 on 2020-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TinhTP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinhtp',
            name='MaTinh',
        ),
    ]
