# Generated by Django 3.0.8 on 2020-07-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TinhTP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuyenQuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenHuyen', models.CharField(max_length=100)),
                ('TinhTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinhTP.TinhTP')),
            ],
        ),
    ]
