# Generated by Django 3.0.4 on 2020-04-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuyenQuan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huyenquan',
            old_name='MaTinh',
            new_name='TinhTP',
        ),
    ]
