# Generated by Django 3.0.4 on 2020-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuyenQuan', '0002_auto_20200401_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huyenquan',
            name='MaHuyen',
        ),
    ]
