# Generated by Django 3.0.8 on 2020-07-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DichVu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DiaChi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('TieuDe', models.CharField(max_length=100)),
                ('Anh', models.ImageField(upload_to='upload_renting_pic')),
                ('Gia', models.DecimalField(decimal_places=3, max_digits=20)),
                ('NgayDang', models.DateField(default=django.utils.timezone.now)),
                ('NgayCapNhat', models.DateField(auto_now=True, db_index=True)),
                ('SDT', models.IntegerField(default=0)),
                ('DienTich', models.IntegerField(default=0)),
                ('NoiDung', models.TextField(max_length=1000)),
                ('DichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DichVu.DichVu')),
                ('NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhongTro', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.province')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.street')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_renting_pic')),
                ('phongtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhongTro.PhongTro')),
            ],
        ),
    ]
