# Generated by Django 3.0.4 on 2020-04-03 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DichVu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HuyenQuan', '0002_auto_20200401_1608'),
        ('TinhTP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaPT', models.IntegerField(default=0)),
                ('TieuDe', models.CharField(max_length=100)),
                ('Anh', models.ImageField(default=None, upload_to='')),
                ('Gia', models.IntegerField(default=0)),
                ('DiaChi', models.CharField(max_length=100)),
                ('NgayDang', models.DateField(default=django.utils.timezone.now)),
                ('SDT', models.IntegerField(default=0)),
                ('DienTich', models.IntegerField(default=0)),
                ('NoiDung', models.CharField(max_length=1000)),
                ('DichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DichVu.DichVu')),
                ('HuyenQuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuyenQuan.HuyenQuan')),
                ('NguoiDung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('TinhTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TinhTP.TinhTP')),
            ],
        ),
    ]
